// Generated by gencpp from file data_handler/GenericData.msg
// DO NOT EDIT!


#ifndef DATA_HANDLER_MESSAGE_GENERICDATA_H
#define DATA_HANDLER_MESSAGE_GENERICDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace data_handler
{
template <class ContainerAllocator>
struct GenericData_
{
  typedef GenericData_<ContainerAllocator> Type;

  GenericData_()
    : header()
    , data()
    , size(0)  {
    }
  GenericData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)
    , size(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;

   typedef uint32_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::data_handler::GenericData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_handler::GenericData_<ContainerAllocator> const> ConstPtr;

}; // struct GenericData_

typedef ::data_handler::GenericData_<std::allocator<void> > GenericData;

typedef boost::shared_ptr< ::data_handler::GenericData > GenericDataPtr;
typedef boost::shared_ptr< ::data_handler::GenericData const> GenericDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_handler::GenericData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_handler::GenericData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_handler::GenericData_<ContainerAllocator1> & lhs, const ::data_handler::GenericData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_handler::GenericData_<ContainerAllocator1> & lhs, const ::data_handler::GenericData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::GenericData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::GenericData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::GenericData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::GenericData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::GenericData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::GenericData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_handler::GenericData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4554f4446943deecd1e823e932614329";
  }

  static const char* value(const ::data_handler::GenericData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4554f4446943deecULL;
  static const uint64_t static_value2 = 0xd1e823e932614329ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_handler::GenericData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_handler/GenericData";
  }

  static const char* value(const ::data_handler::GenericData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_handler::GenericData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8[] data\n"
"uint32 size\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::data_handler::GenericData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_handler::GenericData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenericData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_handler::GenericData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_handler::GenericData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_HANDLER_MESSAGE_GENERICDATA_H
