// Generated by gencpp from file data_handler/RegisterNode.msg
// DO NOT EDIT!


#ifndef DATA_HANDLER_MESSAGE_REGISTERNODE_H
#define DATA_HANDLER_MESSAGE_REGISTERNODE_H

#include <ros/service_traits.h>


#include <data_handler/RegisterNodeRequest.h>
#include <data_handler/RegisterNodeResponse.h>


namespace data_handler
{

struct RegisterNode
{

typedef RegisterNodeRequest Request;
typedef RegisterNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterNode
} // namespace data_handler


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_handler::RegisterNode > {
  static const char* value()
  {
    return "0df1a079a9a4e3ccb2fd3852ded39c15";
  }

  static const char* value(const ::data_handler::RegisterNode&) { return value(); }
};

template<>
struct DataType< ::data_handler::RegisterNode > {
  static const char* value()
  {
    return "data_handler/RegisterNode";
  }

  static const char* value(const ::data_handler::RegisterNode&) { return value(); }
};


// service_traits::MD5Sum< ::data_handler::RegisterNodeRequest> should match 
// service_traits::MD5Sum< ::data_handler::RegisterNode > 
template<>
struct MD5Sum< ::data_handler::RegisterNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_handler::RegisterNode >::value();
  }
  static const char* value(const ::data_handler::RegisterNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_handler::RegisterNodeRequest> should match 
// service_traits::DataType< ::data_handler::RegisterNode > 
template<>
struct DataType< ::data_handler::RegisterNodeRequest>
{
  static const char* value()
  {
    return DataType< ::data_handler::RegisterNode >::value();
  }
  static const char* value(const ::data_handler::RegisterNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_handler::RegisterNodeResponse> should match 
// service_traits::MD5Sum< ::data_handler::RegisterNode > 
template<>
struct MD5Sum< ::data_handler::RegisterNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_handler::RegisterNode >::value();
  }
  static const char* value(const ::data_handler::RegisterNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_handler::RegisterNodeResponse> should match 
// service_traits::DataType< ::data_handler::RegisterNode > 
template<>
struct DataType< ::data_handler::RegisterNodeResponse>
{
  static const char* value()
  {
    return DataType< ::data_handler::RegisterNode >::value();
  }
  static const char* value(const ::data_handler::RegisterNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_HANDLER_MESSAGE_REGISTERNODE_H
