// Generated by gencpp from file data_handler/RegisterHWNodeResponse.msg
// DO NOT EDIT!


#ifndef DATA_HANDLER_MESSAGE_REGISTERHWNODERESPONSE_H
#define DATA_HANDLER_MESSAGE_REGISTERHWNODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_handler
{
template <class ContainerAllocator>
struct RegisterHWNodeResponse_
{
  typedef RegisterHWNodeResponse_<ContainerAllocator> Type;

  RegisterHWNodeResponse_()
    : success(false)  {
    }
  RegisterHWNodeResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterHWNodeResponse_

typedef ::data_handler::RegisterHWNodeResponse_<std::allocator<void> > RegisterHWNodeResponse;

typedef boost::shared_ptr< ::data_handler::RegisterHWNodeResponse > RegisterHWNodeResponsePtr;
typedef boost::shared_ptr< ::data_handler::RegisterHWNodeResponse const> RegisterHWNodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_handler

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'data_handler': ['/home/panda2/Desktop/hric/ws/src/data_handler/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::data_handler::RegisterHWNodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_handler/RegisterHWNodeResponse";
  }

  static const char* value(const ::data_handler::RegisterHWNodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::data_handler::RegisterHWNodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterHWNodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_handler::RegisterHWNodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_handler::RegisterHWNodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_HANDLER_MESSAGE_REGISTERHWNODERESPONSE_H
