// Generated by gencpp from file data_handler/RegisterHWNode.msg
// DO NOT EDIT!


#ifndef DATA_HANDLER_MESSAGE_REGISTERHWNODE_H
#define DATA_HANDLER_MESSAGE_REGISTERHWNODE_H

#include <ros/service_traits.h>


#include <data_handler/RegisterHWNodeRequest.h>
#include <data_handler/RegisterHWNodeResponse.h>


namespace data_handler
{

struct RegisterHWNode
{

typedef RegisterHWNodeRequest Request;
typedef RegisterHWNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterHWNode
} // namespace data_handler


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_handler::RegisterHWNode > {
  static const char* value()
  {
    return "0df1a079a9a4e3ccb2fd3852ded39c15";
  }

  static const char* value(const ::data_handler::RegisterHWNode&) { return value(); }
};

template<>
struct DataType< ::data_handler::RegisterHWNode > {
  static const char* value()
  {
    return "data_handler/RegisterHWNode";
  }

  static const char* value(const ::data_handler::RegisterHWNode&) { return value(); }
};


// service_traits::MD5Sum< ::data_handler::RegisterHWNodeRequest> should match
// service_traits::MD5Sum< ::data_handler::RegisterHWNode >
template<>
struct MD5Sum< ::data_handler::RegisterHWNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_handler::RegisterHWNode >::value();
  }
  static const char* value(const ::data_handler::RegisterHWNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_handler::RegisterHWNodeRequest> should match
// service_traits::DataType< ::data_handler::RegisterHWNode >
template<>
struct DataType< ::data_handler::RegisterHWNodeRequest>
{
  static const char* value()
  {
    return DataType< ::data_handler::RegisterHWNode >::value();
  }
  static const char* value(const ::data_handler::RegisterHWNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_handler::RegisterHWNodeResponse> should match
// service_traits::MD5Sum< ::data_handler::RegisterHWNode >
template<>
struct MD5Sum< ::data_handler::RegisterHWNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_handler::RegisterHWNode >::value();
  }
  static const char* value(const ::data_handler::RegisterHWNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_handler::RegisterHWNodeResponse> should match
// service_traits::DataType< ::data_handler::RegisterHWNode >
template<>
struct DataType< ::data_handler::RegisterHWNodeResponse>
{
  static const char* value()
  {
    return DataType< ::data_handler::RegisterHWNode >::value();
  }
  static const char* value(const ::data_handler::RegisterHWNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_HANDLER_MESSAGE_REGISTERHWNODE_H
