// Generated by gencpp from file data_handler/TestMessage.msg
// DO NOT EDIT!


#ifndef DATA_HANDLER_MESSAGE_TESTMESSAGE_H
#define DATA_HANDLER_MESSAGE_TESTMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_handler
{
template <class ContainerAllocator>
struct TestMessage_
{
  typedef TestMessage_<ContainerAllocator> Type;

  TestMessage_()
    : text()
    , n(0)
    , f(0.0)  {
    }
  TestMessage_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , n(0)
    , f(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef int32_t _n_type;
  _n_type n;

   typedef float _f_type;
  _f_type f;





  typedef boost::shared_ptr< ::data_handler::TestMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_handler::TestMessage_<ContainerAllocator> const> ConstPtr;

}; // struct TestMessage_

typedef ::data_handler::TestMessage_<std::allocator<void> > TestMessage;

typedef boost::shared_ptr< ::data_handler::TestMessage > TestMessagePtr;
typedef boost::shared_ptr< ::data_handler::TestMessage const> TestMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_handler::TestMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_handler::TestMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::data_handler::TestMessage_<ContainerAllocator1> & lhs, const ::data_handler::TestMessage_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.n == rhs.n &&
    lhs.f == rhs.f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::data_handler::TestMessage_<ContainerAllocator1> & lhs, const ::data_handler::TestMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace data_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::TestMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_handler::TestMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::TestMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_handler::TestMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::TestMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_handler::TestMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_handler::TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb3f28b1fb28ea97e948219b8896972";
  }

  static const char* value(const ::data_handler::TestMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabb3f28b1fb28ea9ULL;
  static const uint64_t static_value2 = 0x7e948219b8896972ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_handler::TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_handler/TestMessage";
  }

  static const char* value(const ::data_handler::TestMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_handler::TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"int32 n\n"
"float32 f\n"
;
  }

  static const char* value(const ::data_handler::TestMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_handler::TestMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.n);
      stream.next(m.f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_handler::TestMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_handler::TestMessage_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "n: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n);
    s << indent << "f: ";
    Printer<float>::stream(s, indent + "  ", v.f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_HANDLER_MESSAGE_TESTMESSAGE_H
